### PR TITLE
Add Parameter Store and parameter resolver support

### PR DESCRIPTION
**Pull request by DanielRedOak**
In this PR I added Parameter Store support but stubbed it out a bit to allow support for other providers. I updated the README to include details on use and what others would need to do to add other providers. Let me know how this looks and if you'd like updates!

Inspiration for handling things came from the 'stack_master' project.

### CODE REVIEW

**Comment by DanielRedOak** [comment]
Checking in on this, when might I be able to get some eyes on this? We're currently using it, but I would love to see it merged :)

**Comment by chrisroberts** [comment]
@DanielRedOak Hi and my apologies for the delay! Thanks for being patient. As we were talking about in chat, I really like the enhancement you have created here but there were some things I wanted to refactor to make it a bit more flexible. I have worked off the ideas you had in this changeset and created #20. This new PR does not include a resolver implementation, instead it only contains modifications required to add support for resolvers.

I wanted to allow resolvers to be provided via separate gems instead of requiring them to be included within this library directly (and the dependencies those resolvers may require). The updated implementation registers resolvers when subclassing the Resolver class which allows them to be defined within any namespace. There's some extra bits as well like a setup hook with access to the sfn configuration and memoization of resolver instances so they don't need to be reinstantiated. Would love to get your feedback and thoughts when you have time.

Thanks!

**Comment by DanielRedOak** [comment]
Awesome, thats essentially what I was thinking of I just didn't have time to put the effort in there. Allowing separate Gems will be great. What are your thoughts on maintaining some sort of index or listing for those so people know they exist if they are maintained outside of this project?

I should be able to take a look at the other PR soon. I am going on vacation for a little bit though, but I'd love to see this pushed through so I'll try my best :)

Thanks!

**Comment by webframp** [comment]
I agree, for ease of discovery it might be nice to have a page on the website listing gems

**Comment by chrisroberts** [comment]
Closing this as #20 has been merged. The aws-ssm resolver is not included as this library simply provides the abstract functionality for resolver implementation. I am happy to spin out a repo + rubygem for the ssm resolver implementation if you don't want to own it. Just let me know what you would prefer. Thanks again for this PR and the feedback on the refactoring. Cheers!

**Comment by DanielRedOak** [comment]
@chrisroberts I can spin it up. Should be some copy pasting + a few changes. No big deal

**Pull request closed without merging**
